ALTER TABLE "bookings"
ADD COLUMN "bookingRef" TEXT NOT NULL DEFAULT '',
ADD COLUMN "snapshotJson" JSONB NOT NULL DEFAULT '{}'::jsonb,
ADD COLUMN "clientSnapshotJson" JSONB NOT NULL DEFAULT '{}'::jsonb,
ADD COLUMN "brandSnapshotJson" JSONB,
ADD COLUMN "contactSnapshotJson" JSONB NOT NULL DEFAULT '{}'::jsonb,
ADD COLUMN "itinerarySnapshotJson" JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN "pricingSnapshotJson" JSONB NOT NULL DEFAULT '{}'::jsonb,
ADD COLUMN "adults" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "children" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "roomCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "nightCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "bookings"
ALTER COLUMN "bookingRef" DROP DEFAULT,
ALTER COLUMN "snapshotJson" DROP DEFAULT,
ALTER COLUMN "clientSnapshotJson" DROP DEFAULT,
ALTER COLUMN "contactSnapshotJson" DROP DEFAULT,
ALTER COLUMN "itinerarySnapshotJson" DROP DEFAULT,
ALTER COLUMN "pricingSnapshotJson" DROP DEFAULT,
ALTER COLUMN "adults" DROP DEFAULT,
ALTER COLUMN "children" DROP DEFAULT,
ALTER COLUMN "roomCount" DROP DEFAULT,
ALTER COLUMN "nightCount" DROP DEFAULT,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
