import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

const source = readFileSync(new URL('./RoutePlannerPreview.tsx', import.meta.url), 'utf8');
const workspaceSource = readFileSync(new URL('./QuoteItineraryWorkspace.tsx', import.meta.url), 'utf8');
const presetsSource = readFileSync(new URL('./day-route-presets.ts', import.meta.url), 'utf8');

function expectSourceContains(src: string, fragments: string[]) {
  for (const fragment of fragments) {
    assert.ok(src.includes(fragment), `Expected source to contain: ${fragment}`);
  }
}

describe('Phase S.2D-2 — Route Planner "Apply to Day" (existing day PATCH only)', () => {
  it('renders one row per day with a preset dropdown reusing DAY_ROUTE_PRESETS', () => {
    expectSourceContains(source, [
      'export function RoutePlannerPreview',
      "import { DAY_ROUTE_PRESETS, getDayRoutePreset, getClassicJordanRouteTemplate } from './day-route-presets'",
      'aria-label="Route Planner"',
      'sorted.map((day) =>',
      'Day {String(day.dayNumber).padStart(2, \'0\')}',
      'Current title:',
      'DAY_ROUTE_PRESETS.map((p) =>',
      '<option key={p.key} value={p.key}>{p.label}</option>',
      'Custom / keep current',
      'Leisure / no transport',
      'preset.defaultTitle',
      'preset.narrative',
      'preset.overnightCity',
    ]);
  });

  it('Apply to Day writes ONLY title + notes via the existing PATCH /itinerary/day/:dayId', () => {
    expectSourceContains(source, [
      // explicit, destructive-action button copy
      'Replace Day with Selected Preset',
      // apply handler hits the EXISTING day PATCH endpoint (no new endpoint)
      'async function applyPresetToDay',
      "method: 'PATCH'",
      '`${apiBaseUrl}/itinerary/day/${day.id}`',
      // payload is ONLY the title + client-safe narrative
      'body: JSON.stringify({ title: preset.defaultTitle, notes: preset.narrative })',
      // reuse the standard auth + error helpers + refresh
      'buildAuthHeaders',
      'getErrorMessage',
      'router.refresh()',
      // confirmation before overwriting the day
      'This will replace the current day title and narrative with the selected route preset. Continue?',
    ]);
    // The PATCH body must NOT touch dayNumber / sortOrder / isActive (partial
    // update). Scope the check to JSON.stringify(...) so the header comment that
    // describes the partial update doesn't false-positive.
    assert.ok(!/JSON\.stringify\([^)]*sortOrder/.test(source), 'apply body must not send sortOrder');
    assert.ok(!/JSON\.stringify\([^)]*isActive/.test(source), 'apply body must not send isActive');
    assert.ok(!/JSON\.stringify\([^)]*dayNumber/.test(source), 'apply body must not send dayNumber');
  });

  it('Custom / keep current and Leisure never PATCH; no items / generator / pricing', () => {
    // applyPresetToDay bails when there is no real preset (Custom-keep / Leisure).
    expectSourceContains(source, ['const preset = getDayRoutePreset(presetKey);', 'if (!preset) return;']);
    // No QuoteItem creation, no generator/apply call.
    assert.ok(!/['"`][^'"`]*\/items['"`]/.test(source), 'must not create QuoteItems');
    assert.ok(!source.includes('tailor-made-draft'), 'must not call the generator/apply endpoints');
    // No mutation of the passed-in day objects.
    assert.ok(!/day\.title\s*=/.test(source), 'must not mutate day.title');
    assert.ok(!/day\.narrative\s*=/.test(source), 'must not mutate day narrative');
  });

  it('S.2D-3B/-3C: Classic Jordan Route Template preview + Apply (4/5/6/7-day) via day PATCH', () => {
    expectSourceContains(source, [
      // reuses the merged template constants (no new data)
      "import { DAY_ROUTE_PRESETS, getDayRoutePreset, getClassicJordanRouteTemplate } from './day-route-presets'",
      'const templateKeys = getClassicJordanRouteTemplate(sorted.length)',
      'aria-label="Classic Jordan Route Template"',
      'Classic Jordan Route Template',
      // one preview row per template day with title + overnight + narrative
      'templateKeys.map((key, index) =>',
      'tp?.defaultTitle',
      "tp?.overnightCity ?? 'No overnight (departure day)'",
      'tp?.narrative',
      // 4-day + 5-day warnings (approved copy)
      '4-day classic is a short highlights program. It skips Wadi Rum and gives Petra limited time.',
      '5-day classic is a faster-paced program. It skips Jerash to keep Wadi Rum and Dead Sea.',
      // 8-day → existing-generator note; other durations → basic-shell note
      'The 8-day classic route is currently generated by the existing structured generator.',
      'No curated classic template exists yet. Use the basic shell and edit days manually.',
      // S.2D-3C — Apply Template handler: loops the existing day PATCH (title + notes only)
      'async function applyTemplate',
      'for (let i = 0; i < templateKeys.length; i++)',
      '`${apiBaseUrl}/itinerary/day/${day.id}`',
      "method: 'PATCH'",
      'body: JSON.stringify({ title: tp.defaultTitle, notes: tp.narrative })',
      'router.refresh()',
      // strong confirmation before overwriting multiple days
      'This will replace the current day titles and narratives with the selected Classic Jordan route template. Services and pricing will not be changed. Continue?',
      // day-count guard
      'This template requires ${templateKeys.length} itinerary days. Please create or adjust the itinerary days first.',
      // the Apply button is wired (enabled for templated durations) — only rendered inside the templateKeys branch
      'onClick={applyTemplate}',
      'disabled={applyingTemplate}',
    ]);
    // The template PATCH body must carry ONLY title + notes (scope the field checks
    // to JSON.stringify so the descriptive header comment doesn't false-positive).
    assert.ok(!/JSON\.stringify\([^)]*sortOrder/.test(source), 'template apply body must not send sortOrder');
    assert.ok(!/JSON\.stringify\([^)]*isActive/.test(source), 'template apply body must not send isActive');
    assert.ok(!/JSON\.stringify\([^)]*dayNumber/.test(source), 'template apply body must not send dayNumber');
    // No QuoteItems / generator from the whole component.
    assert.ok(!/['"`][^'"`]*\/items['"`]/.test(source), 'must not create QuoteItems');
    assert.ok(!source.includes('tailor-made-draft'), 'must not call the generator/apply endpoints');
    // The disabled-placeholder + outdated copy are gone (apply is real now).
    assert.ok(!source.includes('Template apply comes in the next phase.'), 'disabled placeholder removed');
    assert.ok(!source.includes('Preview only — templates are not saved yet.'), 'preview-only template copy removed');
    assert.ok(!source.includes('requires a curated departure preset before automation'), 'old 5-day warning removed');
  });

  it('is mounted in the itinerary workspace with apiBaseUrl + day ids', () => {
    expectSourceContains(workspaceSource, [
      "import { RoutePlannerPreview } from './RoutePlannerPreview';",
      '<RoutePlannerPreview',
      'apiBaseUrl={apiBaseUrl}',
      'days={quoteItinerary.days.map((day) => ({ id: day.id, dayNumber: day.dayNumber, title: day.title }))}',
      'id="qb-route-planner"',
    ]);
  });

  it('the preset catalog it reuses is unchanged (no new places exposed here)', () => {
    expectSourceContains(presetsSource, ['export const DAY_ROUTE_PRESETS', 'export const CUSTOM_DAY_PRESET_KEY']);
  });
});
