import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

const source = readFileSync(new URL('./RoutePlannerPreview.tsx', import.meta.url), 'utf8');
const workspaceSource = readFileSync(new URL('./QuoteItineraryWorkspace.tsx', import.meta.url), 'utf8');
const presetsSource = readFileSync(new URL('./day-route-presets.ts', import.meta.url), 'utf8');
const narrativeSource = readFileSync(new URL('./day-narrative-preview.ts', import.meta.url), 'utf8');

function expectSourceContains(src: string, fragments: string[]) {
  for (const fragment of fragments) {
    assert.ok(src.includes(fragment), `Expected source to contain: ${fragment}`);
  }
}

describe('Phase S.2D-2 — Route Planner "Apply to Day" (existing day PATCH only)', () => {
  it('renders one row per day with a preset dropdown reusing DAY_ROUTE_PRESETS', () => {
    expectSourceContains(source, [
      'export function RoutePlannerPreview',
      "import { DAY_ROUTE_PRESETS, getDayRoutePreset, getClassicJordanRouteTemplate } from './day-route-presets'",
      'aria-label="Route Planner"',
      'sorted.map((day) =>',
      'Day {String(day.dayNumber).padStart(2, \'0\')}',
      'Current title:',
      'DAY_ROUTE_PRESETS.map((p) =>',
      '<option key={p.key} value={p.key}>{p.label}</option>',
      'Custom / keep current',
      'Leisure / no transport',
      'preset.defaultTitle',
      'preset.narrative',
      'preset.overnightCity',
    ]);
  });

  it('Apply to Day writes ONLY title + notes via the existing PATCH /itinerary/day/:dayId', () => {
    expectSourceContains(source, [
      // explicit, destructive-action button copy
      'Replace Day with Selected Preset',
      // apply handler hits the EXISTING day PATCH endpoint (no new endpoint)
      'async function applyPresetToDay',
      "method: 'PATCH'",
      '`${apiBaseUrl}/itinerary/day/${day.id}`',
      // payload is ONLY the title + client-safe narrative
      'body: JSON.stringify({ title: preset.defaultTitle, notes: preset.narrative })',
      // reuse the standard auth + error helpers + refresh
      'buildAuthHeaders',
      'getErrorMessage',
      'router.refresh()',
      // confirmation before overwriting the day
      'This will replace the current day title and narrative with the selected route preset. Continue?',
    ]);
    // The PATCH body must NOT touch dayNumber / sortOrder / isActive (partial
    // update). Scope the check to JSON.stringify(...) so the header comment that
    // describes the partial update doesn't false-positive.
    assert.ok(!/JSON\.stringify\([^)]*sortOrder/.test(source), 'apply body must not send sortOrder');
    assert.ok(!/JSON\.stringify\([^)]*isActive/.test(source), 'apply body must not send isActive');
    assert.ok(!/JSON\.stringify\([^)]*dayNumber/.test(source), 'apply body must not send dayNumber');
  });

  it('Custom / keep current and Leisure never PATCH; no items / generator / pricing', () => {
    // applyPresetToDay bails when there is no real preset (Custom-keep / Leisure).
    expectSourceContains(source, ['const preset = getDayRoutePreset(presetKey);', 'if (!preset) return;']);
    // No QuoteItem creation, no generator/apply call.
    assert.ok(!/['"`][^'"`]*\/items['"`]/.test(source), 'must not create QuoteItems');
    assert.ok(!source.includes('tailor-made-draft'), 'must not call the generator/apply endpoints');
    // No mutation of the passed-in day objects.
    assert.ok(!/day\.title\s*=/.test(source), 'must not mutate day.title');
    assert.ok(!/day\.narrative\s*=/.test(source), 'must not mutate day narrative');
  });

  it('S.2D-3B/-3C: Classic Jordan Route Template preview + Apply (4/5/6/7-day) via day PATCH', () => {
    expectSourceContains(source, [
      // reuses the merged template constants (no new data)
      "import { DAY_ROUTE_PRESETS, getDayRoutePreset, getClassicJordanRouteTemplate } from './day-route-presets'",
      'const templateKeys = getClassicJordanRouteTemplate(sorted.length)',
      'aria-label="Classic Jordan Route Template"',
      'Classic Jordan Route Template',
      // one preview row per template day with title + overnight + narrative
      'templateKeys.map((key, index) =>',
      'tp?.defaultTitle',
      "tp?.overnightCity ?? 'No overnight (departure day)'",
      'tp?.narrative',
      // 4-day + 5-day warnings (approved copy)
      '4-day classic is a short highlights program. It skips Wadi Rum and gives Petra limited time.',
      '5-day classic is a faster-paced program. It skips Jerash to keep Wadi Rum and Dead Sea.',
      // 8-day → existing-generator note; other durations → basic-shell note
      'The 8-day classic route is currently generated by the existing structured generator.',
      'No curated classic template exists yet. Use the basic shell and edit days manually.',
      // S.2D-3C — Apply Template handler: loops the existing day PATCH (title + notes only)
      'async function applyTemplate',
      'for (let i = 0; i < templateKeys.length; i++)',
      '`${apiBaseUrl}/itinerary/day/${day.id}`',
      "method: 'PATCH'",
      'body: JSON.stringify({ title: tp.defaultTitle, notes: tp.narrative })',
      'router.refresh()',
      // strong confirmation before overwriting multiple days
      'This will replace the current day titles and narratives with the selected Classic Jordan route template. Services and pricing will not be changed. Continue?',
      // day-count guard
      'This template requires ${templateKeys.length} itinerary days. Please create or adjust the itinerary days first.',
      // the Apply button is wired (enabled for templated durations) — only rendered inside the templateKeys branch
      'onClick={applyTemplate}',
      'disabled={applyingTemplate}',
    ]);
    // The template PATCH body must carry ONLY title + notes (scope the field checks
    // to JSON.stringify so the descriptive header comment doesn't false-positive).
    assert.ok(!/JSON\.stringify\([^)]*sortOrder/.test(source), 'template apply body must not send sortOrder');
    assert.ok(!/JSON\.stringify\([^)]*isActive/.test(source), 'template apply body must not send isActive');
    assert.ok(!/JSON\.stringify\([^)]*dayNumber/.test(source), 'template apply body must not send dayNumber');
    // No QuoteItems / generator from the whole component.
    assert.ok(!/['"`][^'"`]*\/items['"`]/.test(source), 'must not create QuoteItems');
    assert.ok(!source.includes('tailor-made-draft'), 'must not call the generator/apply endpoints');
    // The disabled-placeholder + outdated copy are gone (apply is real now).
    assert.ok(!source.includes('Template apply comes in the next phase.'), 'disabled placeholder removed');
    assert.ok(!source.includes('Preview only — templates are not saved yet.'), 'preview-only template copy removed');
    assert.ok(!source.includes('requires a curated departure preset before automation'), 'old 5-day warning removed');
  });

  it('is mounted in the itinerary workspace with apiBaseUrl + day ids', () => {
    expectSourceContains(workspaceSource, [
      "import { RoutePlannerPreview } from './RoutePlannerPreview';",
      '<RoutePlannerPreview',
      'apiBaseUrl={apiBaseUrl}',
      // R.7A-1/-2 — day notes + applied services are forwarded to the preview.
      'days={quoteItinerary.days.map((day) => ({ id: day.id, dayNumber: day.dayNumber, title: day.title, notes: day.notes, appliedServices: toRoutePlannerAppliedServices(day.dayItems) }))}',
      'id="qb-route-planner"',
      // R.7B-5B — the already-loaded proposal language is forwarded (advisory hint only).
      'proposalLanguage={quote.proposalLanguage ?? null}',
    ]);
    // R.7B-5B — the workspace quote type carries the optional proposalLanguage field
    // (admin-web type only; no backend/schema change).
    expectSourceContains(workspaceSource, ['proposalLanguage?: string | null;']);
  });

  it('maps applied QuoteItems to client-safe service descriptors (R.7A-2)', () => {
    expectSourceContains(workspaceSource, [
      'function toRoutePlannerAppliedServices',
      "{ kind: 'guide' as const }",
      "{ kind: 'hotel' as const }",
      "{ kind: 'transport' as const }",
      // R.7A-2.1 — activity prefers the linked Activity public name (service is null for activities)
      "{ kind: 'activity' as const, name: qs.activityName ?? qs.service?.name ?? null }",
      "{ kind: 'entrance' as const, name: qs.service?.name ?? null }",
    ]);
    // The mapper must NOT forward pricing/supplier/contract/room/meal fields.
    assert.ok(!/appliedVehicleRate\.vehicle|qs\.contract|qs\.roomCategory|pricingDescription|sellPrice|markupPercent/.test(workspaceSource.split('toRoutePlannerAppliedServices')[1]?.slice(0, 600) || ''), 'mapper forwards no pricing/supplier/room fields');
  });

  it('the preset catalog it reuses is unchanged (no new places exposed here)', () => {
    expectSourceContains(presetsSource, ['export const DAY_ROUTE_PRESETS', 'export const CUSTOM_DAY_PRESET_KEY']);
  });
});

describe('Phase R.7A-1 — read-only client narrative preview (route/day text only)', () => {
  it('10/11. renders a "Client narrative preview" per day with the "not saved yet" label', () => {
    expectSourceContains(source, [
      // reuses the pure helper (no network)
      "import { buildDayNarrativePreview, isClientSafeNarrative, narrativeTextDirection, resolveNarrativeLocale, type AppliedNarrativeService, type NarrativeLocale } from './day-narrative-preview'",
      'buildDayNarrativePreview({',
      'title: day.title',
      'notes: day.notes',
      // the read-only block + copy
      'aria-label="Client narrative preview"',
      'Client narrative preview',
      'narrativePreview.text',
      'Preview only — not saved yet',
    ]);
    // R.7A-3 adds an opt-in "Use this narrative" save action; the "Preview only —
    // not saved yet" flag still renders (the preview itself is never auto-saved).
    assert.ok(source.includes('Use this narrative'), 'R.7A-3 save action present');
    assert.ok(source.includes('Preview only — not saved yet'), 'preview-not-saved flag retained');
  });

  it('R.7A-2: forwards applied services + shows "Includes applied services" only when service-aware', () => {
    expectSourceContains(source, [
      // helper import now also pulls the applied-service type
      "import { buildDayNarrativePreview, isClientSafeNarrative, narrativeTextDirection, resolveNarrativeLocale, type AppliedNarrativeService, type NarrativeLocale } from './day-narrative-preview'",
      // applied services threaded into the preview helper
      'appliedServices: day.appliedServices',
      // conditional label, only when the preview actually wove services in
      "narrativePreview.sourceLayer === 'service-aware'",
      'Includes applied services',
    ]);
  });

  it('12/13/14/15. the preview adds no write/network/proposal/pricing coupling', () => {
    // No suggestion endpoints called from the component (route/day text only).
    assert.ok(!source.includes('tailor-made-draft'), 'preview must not call suggestion/generator endpoints');
    // The only network calls are day-PATCH apply handlers: the two pre-existing
    // (S.2D-2 applyPresetToDay, S.2D-3C applyTemplate) + R.7A-3 applyNarrativeToDay
    // (notes-only) + P.3X-5E-5B bulkSaveNarratives (notes + notesLanguage). All PATCH
    // /itinerary/day; no POST/DELETE, no /items, no generator.
    const patchCount = (source.match(/method:\s*['"]PATCH['"]/g) || []).length;
    assert.equal(patchCount, 4, 'four day-PATCH apply handlers (preset, template, R.7A-3 narrative, P.3X-5E-5B bulk)');
    assert.ok(!/method:\s*['"](POST|DELETE)['"]/.test(source), 'no POST/DELETE added');
    // The pure helper itself performs no I/O (call-shaped checks, so its own
    // descriptive header comment — "NO PATCH", "NO proposal-v3 change" — doesn't
    // false-positive).
    assert.ok(!/fetch\s*\(/.test(narrativeSource), 'helper makes no network calls');
    assert.ok(!/useRouter|router\.\w+\(/.test(narrativeSource), 'helper does not navigate/refresh');
    assert.ok(!/method:\s*['"]/.test(narrativeSource), 'helper issues no HTTP method');
  });
});

describe('R.7A-3 — "Use this narrative" saves the day narrative to notes (notes-only PATCH)', () => {
  it('renders a Use this narrative button gated on a client-safe preview', () => {
    expectSourceContains(source, [
      "import { buildDayNarrativePreview, isClientSafeNarrative, narrativeTextDirection, resolveNarrativeLocale, type AppliedNarrativeService, type NarrativeLocale } from './day-narrative-preview'",
      'Use this narrative',
      'const canSave = isClientSafeNarrative(narrativePreview.text)',
      'disabled={!canSave || savingThis}',
      // R.7B-4 — the save now passes the selected locale (English still uses 'en').
      'onClick={() => applyNarrativeToDay(day, narrativePreview.text, narrativeLocaleForDay)}',
      // empty/unsafe disables save + shows a clear message
      'Narrative preview is empty or not client-safe — it cannot be saved to the day notes.',
      // success state
      'Saved to day notes. The preview now matches the saved notes.',
    ]);
  });

  it('confirms before overwrite, with a stronger warning when notes look manually edited', () => {
    expectSourceContains(source, [
      'function isManuallyEditedNotes(day: RoutePlannerDay, generatedText: string)',
      'PRESET_NARRATIVES.has(notes)',
      // English confirmation copy is unchanged (R.7A-3); the manual-edit prefix is shared.
      'This will replace the current day narrative/notes with the client narrative preview. Continue?',
      'This day’s notes may have been manually edited. Replacing them may overwrite operator changes.',
      'window.confirm(message)',
    ]);
  });

  it('saves via the EXISTING day PATCH with a { notes, notesLanguage } payload', () => {
    // Phase P.3X-5E-4B — the save now ALSO records the language (notesLanguage = the
    // selected locale) so the proposal export can detect mismatches precisely. It is
    // still ONLY notes + notesLanguage — no title / dayNumber / services / pricing.
    expectSourceContains(source, [
      'async function applyNarrativeToDay(day: RoutePlannerDay, generatedText: string, locale: NarrativeLocale)',
      '`${apiBaseUrl}/itinerary/day/${day.id}`',
      "method: 'PATCH'",
      'JSON.stringify({ notes: generatedText, notesLanguage: locale })',
      'router.refresh()',
    ]);
    const handlerStart = source.indexOf('async function applyNarrativeToDay');
    const handler = source.slice(handlerStart, source.indexOf('\n  }', handlerStart) + 4);
    const payloadMatch = handler.match(/JSON\.stringify\((\{[^}]*\})\)/);
    assert.ok(payloadMatch, 'narrative save has a JSON.stringify payload');
    const payload = payloadMatch![1];
    assert.ok(payload.includes('notes'), 'payload includes notes');
    assert.ok(payload.includes('notesLanguage'), 'payload records the language');
    for (const forbidden of ['title', 'dayNumber', 'sortOrder', 'isActive', 'country', 'serviceId', 'poi', 'markup', 'overrideCost', 'paxCount', 'price']) {
      assert.ok(!payload.includes(forbidden), `narrative save payload must not include ${forbidden}`);
    }
  });

  it('exposes the client-safe save guard from the pure narrative module', () => {
    expectSourceContains(narrativeSource, ['export function isClientSafeNarrative']);
  });
});

describe('R.7B-3B — narrative language selector + RTL preview (preview-only)', () => {
  it('1/2. preview defaults to English and renders in the selected language', () => {
    expectSourceContains(source, [
      // 4 supported preview languages
      "{ code: 'en', label: 'English' }",
      "{ code: 'es', label: 'Spanish' }",
      "{ code: 'pt', label: 'Portuguese' }",
      "{ code: 'ar', label: 'Arabic' }",
      // per-day language state, default English
      'const [narrativeLocale, setNarrativeLocale] = useState<Record<number, NarrativeLocale>>({})',
      'const narrativeLocaleForDay: NarrativeLocale = narrativeLocale[day.dayNumber] ?? \'en\'',
      // the selector itself
      'Preview language',
      'value={narrativeLocaleForDay}',
      'setNarrativeLocale((prev) => ({ ...prev, [day.dayNumber]: resolveNarrativeLocale(e.target.value) }))',
      'NARRATIVE_LANGUAGE_OPTIONS.map((opt) =>',
      // the selected locale drives the preview render
      '}, { locale: narrativeLocaleForDay });',
    ]);
  });

  it('3/4/5/6/7. preview text uses narrativeTextDirection for dir (Arabic rtl, others ltr)', () => {
    expectSourceContains(source, [
      'const narrativeDir = narrativeTextDirection(narrativeLocaleForDay)',
      'dir={narrativeDir}',
      'lang={narrativeLocaleForDay}',
    ]);
    // the direction helper itself maps ar → rtl, en/es/pt → ltr (asserted at the source)
    expectSourceContains(narrativeSource, [
      "return locale === 'ar' ? 'rtl' : 'ltr';",
    ]);
  });

  it('keeps the language selector; the save label is English by default (R.7B-4 enables non-English saves)', () => {
    expectSourceContains(source, [
      'const narrativeIsEnglish = narrativeLocaleForDay === \'en\'',
      // English keeps its original button label
      "? 'Use this narrative'",
    ]);
    // R.7B-4 removed the "saving is a later phase" placeholder — it now saves.
    assert.ok(!source.includes('Saving translated narratives will be enabled in a later phase.'), 'later-phase placeholder removed');
  });

  it('the language selector adds no new PATCH; the save records the locale as notesLanguage', () => {
    // The narrative save reuses the existing day-PATCH; no new endpoint is added.
    // Phase P.3X-5E-4B — the selected locale is now sent as notesLanguage metadata
    // (capture-only); still no new request and no pricing/services.
    const patchCount = (source.match(/method:\s*['"]PATCH['"]/g) || []).length;
    assert.equal(patchCount, 4, 'no new PATCH added beyond the P.3X-5E-5B bulk handler');
    assert.ok(!/method:\s*['"](POST|DELETE)['"]/.test(source), 'no POST/DELETE added');
    const onClickCount = (source.match(/onClick=\{\(\) => applyNarrativeToDay\(/g) || []).length;
    assert.equal(onClickCount, 1, 'narrative save is wired once');
    assert.ok(/JSON\.stringify\(\{ notes: generatedText, notesLanguage: locale \}\)/.test(source), 'save records notesLanguage = selected locale');
  });

  it('13. no proposal/backend/schema/pricing/QuoteItem/apply-flow coupling added', () => {
    assert.ok(!source.includes('tailor-made-draft'), 'no generator/apply endpoints');
    assert.ok(!/['"`][^'"`]*\/items['"`]/.test(source), 'no QuoteItem creation');
    // R.7B-5B — the component reads the quote's `proposalLanguage` (data only) for an
    // advisory hint; assert no proposal-v3 RENDERING coupling (no module import / no
    // proposal endpoint fetch) rather than banning the word "proposal".
    assert.ok(!/proposal-v3|getProposalHtml|getProposalPdf|['"`][^'"`]*\/proposal[^'"`]*['"`]/i.test(source), 'no proposal-v3 rendering coupling');
  });
});

describe('R.7B-4 — save the selected-language narrative into day notes (notes-only)', () => {
  it('1. English save behaviour is unchanged (label + exact confirm copy + en path)', () => {
    expectSourceContains(source, [
      // English keeps the original button label …
      "? 'Use this narrative'",
      // … selects on the en locale …
      "locale === 'en'",
      // … and keeps the original English confirmation copy (no language suffix).
      '`${manualPrefix}This will replace the current day narrative/notes with the client narrative preview. Continue?`',
    ]);
  });

  it('2/3/4. save is enabled per language; the button + handler carry the selected locale', () => {
    expectSourceContains(source, [
      // language label map (en/es/pt/ar)
      'const NARRATIVE_LANGUAGE_LABELS: Record<NarrativeLocale, string> = {',
      "es: 'Spanish'",
      "pt: 'Portuguese'",
      "ar: 'Arabic'",
      // non-English button label: "Use this Spanish/Portuguese/Arabic narrative"
      '`Use this ${NARRATIVE_LANGUAGE_LABELS[narrativeLocaleForDay]} narrative`',
      // the save passes the selected locale through to the handler
      'onClick={() => applyNarrativeToDay(day, narrativePreview.text, narrativeLocaleForDay)}',
      'async function applyNarrativeToDay(day: RoutePlannerDay, generatedText: string, locale: NarrativeLocale)',
    ]);
  });

  it('5. non-English confirmation names the language + warns notes stores one language', () => {
    expectSourceContains(source, [
      'This will replace the current day notes with the ${NARRATIVE_LANGUAGE_LABELS[locale]} narrative. Continue?',
      'Day notes stores only one language. Saving this will replace the current notes with the selected-language text.',
    ]);
  });

  it('6. manual-edit warning is still applied (shared prefix)', () => {
    expectSourceContains(source, [
      'const manual = isManuallyEditedNotes(day, generatedText)',
      'This day’s notes may have been manually edited. Replacing them may overwrite operator changes.',
    ]);
  });

  it('7/8/9/10. PATCH is notes + notesLanguage only — no title/pricing/services, no sibling writes', () => {
    // Phase P.3X-5E-4B — the day PATCH now carries the notes AND notesLanguage (the
    // selected locale, capture-only). It still carries nothing else: no title /
    // dayNumber / pricing / services / POIs, and no loop over sibling days.
    const handlerStart = source.indexOf('async function applyNarrativeToDay');
    const handler = source.slice(handlerStart, source.indexOf('\n  }', handlerStart) + 4);
    const payload = handler.match(/JSON\.stringify\((\{[^}]*\})\)/)![1];
    assert.equal(payload.replace(/\s/g, ''), '{notes:generatedText,notesLanguage:locale}', 'payload is exactly { notes, notesLanguage }');
    for (const forbidden of ['title', 'dayNumber', 'sortOrder', 'isActive', 'country', 'poi', 'serviceId', 'price', 'markup']) {
      assert.ok(!payload.includes(forbidden), `payload must not include ${forbidden}`);
    }
    assert.ok(source.includes('`${apiBaseUrl}/itinerary/day/${day.id}`'), 'targets the selected day id');
  });

  it('11. empty/unsafe preview still disables save (guard retained)', () => {
    expectSourceContains(source, [
      'const canSave = isClientSafeNarrative(narrativePreview.text)',
      'disabled={!canSave || savingThis}',
      'if (!isClientSafeNarrative(generatedText)) return;',
    ]);
  });

  it('12. Arabic preview still renders rtl (selector + direction unchanged)', () => {
    expectSourceContains(source, ['dir={narrativeDir}', 'const narrativeDir = narrativeTextDirection(narrativeLocaleForDay)']);
    expectSourceContains(narrativeSource, ["return locale === 'ar' ? 'rtl' : 'ltr';"]);
  });

  it('13/14. no backend/proposal/schema/pricing/QuoteItem/apply coupling; notes-only single-day write', () => {
    assert.ok(!source.includes('tailor-made-draft'), 'no generator/apply endpoints');
    assert.ok(!/['"`][^'"`]*\/items['"`]/.test(source), 'no QuoteItem creation');
    // R.7B-5B — the component reads the quote's `proposalLanguage` (data only) for an
    // advisory hint; assert no proposal-v3 RENDERING coupling (no module import / no
    // proposal endpoint fetch) rather than banning the word "proposal".
    assert.ok(!/proposal-v3|getProposalHtml|getProposalPdf|['"`][^'"`]*\/proposal[^'"`]*['"`]/i.test(source), 'no proposal-v3 rendering coupling');
    // Now four day-PATCH handlers (preset, template, narrative, P.3X-5E-5B bulk).
    assert.equal((source.match(/method:\s*['"]PATCH['"]/g) || []).length, 4, 'no new PATCH added beyond the P.3X-5E-5B bulk handler');
  });
});

describe('R.7B-5B — proposal-language mismatch hints (advisory, non-blocking)', () => {
  it('reads the quote proposal language (data only) and normalizes it', () => {
    expectSourceContains(source, [
      // new advisory-only prop (already-loaded data, no backend call)
      'proposalLanguage?: string | null;',
      // normalized to a NarrativeLocale (en/es/pt/ar) for comparison
      'const quoteProposalLocale: NarrativeLocale = resolveNarrativeLocale(proposalLanguage)',
    ]);
  });

  it('1/2/3/4. warns when the selected preview language differs from the proposal language', () => {
    expectSourceContains(source, [
      'const previewLanguageMismatch = narrativeLocaleForDay !== quoteProposalLocale',
      // advisory copy naming both languages
      'The selected narrative language is {NARRATIVE_LANGUAGE_LABELS[narrativeLocaleForDay]}, but the proposal',
      'language is {NARRATIVE_LANGUAGE_LABELS[quoteProposalLocale]}. Saving this may create a mixed-language proposal.',
      // gated render
      '{previewLanguageMismatch ? (',
    ]);
  });

  it('5/6/7. warns when saved notes look Arabic and the proposal is not Arabic (Arabic-only detector)', () => {
    expectSourceContains(source, [
      'const savedNotesLookArabic = ARABIC_SCRIPT_PATTERN.test(day.notes || \'\')',
      // only flags when the proposal language is NOT Arabic (#6: ar proposal → no warning)
      "const savedNotesArabicMismatch = savedNotesLookArabic && quoteProposalLocale !== 'ar'",
      'This day’s saved notes appear to be Arabic, but the proposal language is {NARRATIVE_LANGUAGE_LABELS[quoteProposalLocale]}.',
      '{savedNotesArabicMismatch ? (',
    ]);
    // The detector is Arabic-script only — Latin text (en/es/pt) is never flagged (#7).
    const m = source.match(/const ARABIC_SCRIPT_PATTERN = (\/\[[^\n]*?\]\/);/);
    assert.ok(m, 'ARABIC_SCRIPT_PATTERN defined as a regex literal');
    const re = eval(m![1]) as RegExp;
    assert.equal(re.test('عمّان'), true, 'matches Arabic');
    assert.equal(re.test('Amman'), false, 'does not match Latin English');
    assert.equal(re.test('Petra, la ciudad rosada'), false, 'does not match Latin Spanish');
  });

  it('8/9/10/11. hints are advisory — save is the { notes, notesLanguage } day PATCH, nothing more', () => {
    // No new PATCH/POST; the advisory mismatch HINTS add no request of their own.
    // (Four PATCH handlers total after the P.3X-5E-5B bulk save; none from the hints.)
    assert.equal((source.match(/method:\s*['"]PATCH['"]/g) || []).length, 4, 'no new PATCH added by the hints (bulk handler is separate)');
    assert.ok(!/method:\s*['"](POST|DELETE)['"]/.test(source), 'no POST/DELETE added');
    // The narrative-save PATCH body is exactly { notes, notesLanguage } (P.3X-5E-4B).
    const handlerStart = source.indexOf('async function applyNarrativeToDay');
    const handler = source.slice(handlerStart, source.indexOf('\n  }', handlerStart) + 4);
    const payload = handler.match(/JSON\.stringify\((\{[^}]*\})\)/)![1];
    assert.equal(payload.replace(/\s/g, ''), '{notes:generatedText,notesLanguage:locale}', 'save payload is { notes, notesLanguage }');
    // Hints never disable/guard the save button or the preview.
    assert.ok(!/disabled=\{[^}]*Mismatch/.test(source), 'mismatch never disables a control');
  });

  it('12. Arabic preview direction is still rtl (selector/direction unchanged)', () => {
    expectSourceContains(source, ['dir={narrativeDir}', 'const narrativeDir = narrativeTextDirection(narrativeLocaleForDay)']);
    expectSourceContains(narrativeSource, ["return locale === 'ar' ? 'rtl' : 'ltr';"]);
  });
});

describe('P.3X-5E-5B — bulk "Save all day narratives in one language"', () => {
  // Isolate the bulk handler body for payload + control-flow assertions.
  const handlerStart = source.indexOf('async function bulkSaveNarratives');
  const handler = source.slice(handlerStart, source.indexOf('\n  }', handlerStart) + 4);

  it('1/3/4/5. renders a bulk action with a language selector + per-language button label (en/es/pt/ar)', () => {
    expectSourceContains(source, [
      'aria-label="Bulk save day narratives"',
      'Save all day narratives in one language',
      // language selector bound to the bulk locale state (reuses the 4-language list)
      'const [bulkLocale, setBulkLocale] = useState<NarrativeLocale>(quoteProposalLocale)',
      'value={bulkLocale}',
      'onChange={(e) => setBulkLocale(resolveNarrativeLocale(e.target.value))}',
      'NARRATIVE_LANGUAGE_OPTIONS.map((opt) =>',
      // #2 — the selected language is shown clearly
      'Selected language: {NARRATIVE_LANGUAGE_LABELS[bulkLocale]}',
      // language-specific button label → "Save all Spanish/Portuguese/Arabic/English narratives"
      '`Save all ${NARRATIVE_LANGUAGE_LABELS[bulkLocale]} narratives`',
      'onClick={() => bulkSaveNarratives(bulkLocale)}',
      // the handler reuses the deterministic R.7B generator, same input shape as per-day save
      'buildDayNarrativePreview(',
      '{ dayNumber: day.dayNumber, title: day.title, notes: day.notes, appliedServices: day.appliedServices }',
      '{ locale }',
    ]);
  });

  it('2/11. each successful PATCH sends ONLY { notes, notesLanguage } via the existing day endpoint', () => {
    expectSourceContains(handler, [
      '`${apiBaseUrl}/itinerary/day/${day.id}`',
      "method: 'PATCH'",
      'JSON.stringify({ notes: text, notesLanguage: locale })',
    ]);
    const payload = handler.match(/JSON\.stringify\((\{[^}]*\})\)/)![1];
    assert.equal(payload.replace(/\s/g, ''), '{notes:text,notesLanguage:locale}', 'bulk payload is exactly { notes, notesLanguage }');
    // #9 — must NOT send any of these forbidden fields.
    for (const forbidden of ['title', 'dayNumber', 'sortOrder', 'isActive', 'country', 'poi', 'serviceId', 'service', 'price', 'markup', 'overrideCost', 'paxCount', 'proposalLanguage']) {
      assert.ok(!payload.includes(forbidden), `bulk payload must not include ${forbidden}`);
    }
  });

  it('6. confirmation lists affected days (number + current title) with the strong warning copy', () => {
    expectSourceContains(handler, [
      // strong warning copy: replaces notes / single-language / one-at-a-time / what it does NOT touch
      'This will replace the notes for all itinerary days with ${label} client narratives.',
      'Day notes store only one language.',
      'Each day will be patched one at a time.',
      'This does not change titles, services, pricing, QuoteItems, POIs, or proposal settings.',
      // #4 — affected day list (number + title)
      'Affected days (${affected.length}):',
      '`  • Day ${String(p.day.dayNumber).padStart(2, \'0\')} — ${p.day.title?.trim() || `Day ${p.day.dayNumber}`}`',
      'window.confirm(message)',
    ]);
  });

  it('7. cancel → no PATCH (early return before the loop)', () => {
    assert.ok(/if \(typeof window !== 'undefined' && !window\.confirm\(message\)\) \{\s*return;/.test(handler), 'cancel returns before any fetch');
    // The confirm gate appears before the fetch in the handler body.
    assert.ok(handler.indexOf('window.confirm(message)') < handler.indexOf('fetch('), 'confirm precedes the PATCH');
  });

  it('8/13. days already in the target language are skipped by default and reported', () => {
    expectSourceContains(handler, [
      'alreadyMatching: (day.notesLanguage ?? null) === locale',
      'const affected = plan.filter((p) => !p.alreadyMatching)',
      'const alreadyMatching = plan.filter((p) => p.alreadyMatching).map((p) => p.day.dayNumber)',
      // skip reason recorded in the result
      'reason: `already in ${label}`',
    ]);
  });

  it('9/10. empty/unsafe generated narrative is skipped (not patched) and reported', () => {
    expectSourceContains(handler, [
      'if (!isClientSafeNarrative(text)) {',
      "reason: 'generated narrative empty or not client-safe'",
      'continue;',
    ]);
    // the safety guard precedes the fetch
    assert.ok(handler.indexOf('isClientSafeNarrative(text)') < handler.indexOf('fetch('), 'safety guard precedes PATCH');
  });

  it('11. honest partial failure — per-day saved/skipped/failed, no rollback', () => {
    expectSourceContains(handler, [
      'const saved: number[] = []',
      'const failed: { day: number; reason: string }[] = []',
      // a failed PATCH is recorded and the loop continues (no throw, no rollback)
      "failed.push({ day: day.dayNumber, reason: await getErrorMessage(response, 'save failed') })",
      'setBulkResult({ saved, skipped, failed })',
    ]);
    // result rendering surfaces all three buckets
    expectSourceContains(source, [
      'Saved {NARRATIVE_LANGUAGE_LABELS[bulkLocale]} narratives to day(s):',
      'Skipped day(s):',
      'Failed day(s):',
      'Earlier saved days were kept.',
    ]);
  });

  it('14/18. no proposal/backend/schema/pricing/QuoteItem coupling; generator emits plain text (no markup)', () => {
    // No QuoteItem creation, no generator/suggestion endpoints, no proposal-v3 rendering.
    assert.ok(!source.includes('tailor-made-draft'), 'no generator/apply endpoints');
    assert.ok(!/['"`][^'"`]*\/items['"`]/.test(source), 'no QuoteItem creation');
    assert.ok(!/proposal-v3|getProposalHtml|getProposalPdf|['"`][^'"`]*\/proposal[^'"`]*['"`]/i.test(source), 'no proposal-v3 rendering coupling');
    // #18 — the bulk save persists the generator's text verbatim (the pure helper
    // emits plain text, incl. Arabic); the handler does not wrap it in any markup.
    assert.ok(/notes: text\b/.test(handler), 'saves the generated text as-is (plain text)');
    assert.ok(!/<[a-z]+>|dangerouslySetInnerHTML/i.test(handler), 'bulk handler injects no HTML/markup');
  });

  it('17. existing per-day "Use this narrative" save is unchanged (still notes + notesLanguage)', () => {
    expectSourceContains(source, [
      'async function applyNarrativeToDay(day: RoutePlannerDay, generatedText: string, locale: NarrativeLocale)',
      'JSON.stringify({ notes: generatedText, notesLanguage: locale })',
      'onClick={() => applyNarrativeToDay(day, narrativePreview.text, narrativeLocaleForDay)}',
    ]);
    // exactly one per-day narrative-save wiring remains
    assert.equal((source.match(/onClick=\{\(\) => applyNarrativeToDay\(/g) || []).length, 1, 'per-day save wired once');
  });
});
