// Demo / fallback data ONLY.
//
// This is the single place mock content lives. Use it for previews, Storybook,
// tests, or as a fallback when a real quote has not loaded. In production,
// fetch a real quote from your API/Prisma and pass it to <QuoteBuilderV2 />
// instead of importing this file.

import type { Quote, WorkflowStep } from "./quote-types"

const steps: WorkflowStep[] = [
  { id: "setup", label: "Setup", description: "Client & trip basics", status: "complete" },
  { id: "itinerary", label: "Itinerary", description: "Day-by-day program", status: "complete" },
  { id: "hotels", label: "Hotels", description: "Accommodation & rooming", status: "partial" },
  { id: "experiences", label: "Experiences", description: "Visits & entrances", status: "partial" },
  { id: "transport", label: "Transport", description: "Vehicles & transfers", status: "partial" },
  { id: "passengers", label: "Passengers", description: "Travellers & rooming", status: "complete" },
  { id: "pricing", label: "Pricing", description: "Costs & margin", status: "partial" },
  { id: "proposal", label: "Proposal", description: "Review & generate PDF", status: "missing" },
]

export const demoQuote: Quote = {
  id: "AVX-26-JO-0142",
  meta: {
    title: "Classic Jordan Discovery — 8 Days / 7 Nights",
    reference: "AVX-26-JO-0142",
    quoteType: "Group",
    destination: "Jordan",
    marketLanguage: "English (UK)",
    startDate: "2026-04-11",
    endDate: "2026-04-18",
    nights: 7,
    pax: 28,
    tourLeaders: 2,
    rooming: "12 DBL · 2 TWN · 2 SGL",
    currency: "USD",
    status: "draft",
    owner: "Lina Haddad",
    lastSaved: "3 minutes ago",
  },
  client: {
    id: "cl-horizon",
    contactName: "Sarah Whitfield",
    contactEmail: "sarah@horizonjourneys.co.uk",
    agency: {
      id: "ag-horizon",
      name: "Horizon Journeys (UK)",
      country: "United Kingdom",
      marketLanguage: "English (UK)",
    },
  },
  steps,
  setupFields: [
    { group: "client", label: "Agency / Client", value: "Horizon Journeys (UK)" },
    { group: "client", label: "Booking contact", value: "Sarah Whitfield" },
    { group: "client", label: "Market & language", value: "United Kingdom — English (UK)" },
    { group: "client", label: "Quote type", value: "Group (GIT)" },
    { group: "trip", label: "Destination", value: "Jordan" },
    { group: "trip", label: "Gateway", value: "Queen Alia Intl (AMM)" },
    { group: "trip", label: "Travel dates", value: "11 Apr – 18 Apr 2026" },
    { group: "trip", label: "Duration", value: "8 days / 7 nights" },
    { group: "config", label: "Pax", value: "28 travellers + 2 tour leaders" },
    { group: "config", label: "Rooming", value: "12 DBL · 2 TWN · 2 SGL" },
    { group: "config", label: "Currency", value: "USD ($)" },
    { group: "config", label: "Operations owner", value: "Lina Haddad" },
  ],
  itinerary: [
    {
      id: "d1",
      day: 1,
      date: "Sat 11 Apr",
      overnightCity: "Amman",
      title: "Arrival at Queen Alia & Welcome",
      visits: ["Airport meet & greet, fast-track", "Evening welcome briefing"],
      meals: ["D"],
      hotelAssigned: "Kempinski Hotel Amman",
      transportAssigned: "Arrival transfer — 35-seat coach",
      warnings: [],
    },
    {
      id: "d2",
      day: 2,
      date: "Sun 12 Apr",
      overnightCity: "Amman",
      title: "Amman City Tour & Jerash",
      visits: ["Amman Citadel", "Roman Theatre", "Jerash Greco-Roman ruins"],
      meals: ["B", "L"],
      hotelAssigned: "Kempinski Hotel Amman",
      transportAssigned: "Full-day touring — 35-seat coach",
      warnings: [],
    },
    {
      id: "d3",
      day: 3,
      date: "Mon 13 Apr",
      overnightCity: "Petra",
      title: "King's Highway to Petra",
      visits: ["Madaba mosaic map", "Mount Nebo", "Kerak Castle"],
      meals: ["B", "D"],
      hotelAssigned: "Mövenpick Resort Petra",
      transportAssigned: "Intercity transfer — 35-seat coach",
      warnings: [],
    },
    {
      id: "d4",
      day: 4,
      date: "Tue 14 Apr",
      overnightCity: "Petra",
      title: "Petra Full Day",
      visits: ["The Siq & Treasury", "Royal Tombs", "Ad-Deir (Monastery)"],
      meals: ["B", "L"],
      hotelAssigned: "Mövenpick Resort Petra",
      transportAssigned: "Walking program — no vehicle required",
      warnings: [],
    },
    {
      id: "d5",
      day: 5,
      date: "Wed 15 Apr",
      overnightCity: "Wadi Rum",
      title: "Little Petra & Wadi Rum Desert",
      visits: ["Little Petra (Siq al-Barid)", "Wadi Rum 4x4 safari", "Sunset over the dunes"],
      meals: ["B", "L", "D"],
      hotelAssigned: null,
      transportAssigned: null,
      warnings: ["No desert camp assigned for overnight", "Wadi Rum 4x4 supplier not confirmed"],
    },
    {
      id: "d6",
      day: 6,
      date: "Thu 16 Apr",
      overnightCity: "Dead Sea",
      title: "Wadi Rum to the Dead Sea",
      visits: ["Desert sunrise", "Transfer via Desert Highway", "Dead Sea float & leisure"],
      meals: ["B", "D"],
      hotelAssigned: "Kempinski Hotel Ishtar Dead Sea",
      transportAssigned: "Intercity transfer — 35-seat coach",
      warnings: ["Dead Sea hotel still on request"],
    },
    {
      id: "d7",
      day: 7,
      date: "Fri 17 Apr",
      overnightCity: "Dead Sea",
      title: "Bethany & Dead Sea Leisure",
      visits: ["Bethany Beyond the Jordan (Baptism Site)", "Afternoon at leisure"],
      meals: ["B"],
      hotelAssigned: "Kempinski Hotel Ishtar Dead Sea",
      transportAssigned: null,
      warnings: ["No transport assigned for Baptism Site half-day"],
    },
    {
      id: "d8",
      day: 8,
      date: "Sat 18 Apr",
      overnightCity: "Departure",
      title: "Departure Transfer",
      visits: ["Hotel to Queen Alia International Airport"],
      meals: ["B"],
      hotelAssigned: null,
      transportAssigned: "Departure transfer — 35-seat coach",
      warnings: [],
    },
  ],
  hotelCities: [
    {
      city: "Amman",
      nights: 2,
      options: [
        { id: "amm-1", name: "Kempinski Hotel Amman", city: "Amman", category: 5, contractStatus: "contracted", mealPlan: "Bed & Breakfast", roomingSummary: "12 DBL · 2 TWN · 2 SGL", ratePerNight: 215, nights: 2, selected: true, editable: true, optionId: "demo-set-1", cityTax: 6 },
        { id: "amm-2", name: "Fairmont Amman", city: "Amman", category: 5, contractStatus: "on-request", mealPlan: "Bed & Breakfast", roomingSummary: "—", ratePerNight: 198, nights: 2, selected: false, editable: true, optionId: "demo-set-1", cityTax: 6 },
      ],
    },
    {
      city: "Petra",
      nights: 2,
      options: [
        { id: "ptr-1", name: "Mövenpick Resort Petra", city: "Petra", category: 5, contractStatus: "contracted", mealPlan: "Half Board", roomingSummary: "12 DBL · 2 TWN · 2 SGL", ratePerNight: 240, nights: 2, selected: true, editable: true, optionId: "demo-set-1", cityTax: 4 },
        { id: "ptr-2", name: "Petra Marriott Hotel", city: "Petra", category: 5, contractStatus: "contracted", mealPlan: "Half Board", roomingSummary: "—", ratePerNight: 205, nights: 2, selected: false, editable: true, optionId: "demo-set-1", cityTax: 4 },
      ],
    },
    {
      city: "Wadi Rum",
      nights: 1,
      options: [
        { id: "wr-1", name: "Memories Aicha Luxury Camp", city: "Wadi Rum", category: "Camp", contractStatus: "on-request", mealPlan: "Half Board", roomingSummary: "Pending availability", ratePerNight: 180, nights: 1, selected: false, editable: true, optionId: "demo-set-1", cityTax: 0 },
        { id: "wr-2", name: "Sun City Camp (Martian Dome)", city: "Wadi Rum", category: "Camp", contractStatus: "no-contract", mealPlan: "Half Board", roomingSummary: "—", ratePerNight: 165, nights: 1, selected: false, editable: true, optionId: "demo-set-1", cityTax: 0 },
      ],
    },
    {
      city: "Dead Sea",
      nights: 2,
      options: [
        { id: "ds-1", name: "Kempinski Hotel Ishtar Dead Sea", city: "Dead Sea", category: 5, contractStatus: "on-request", mealPlan: "Bed & Breakfast", roomingSummary: "12 DBL · 2 TWN · 2 SGL", ratePerNight: 260, nights: 2, selected: true, editable: true, optionId: "demo-set-1", cityTax: 5 },
        { id: "ds-2", name: "Mövenpick Resort & Spa Dead Sea", city: "Dead Sea", category: 5, contractStatus: "contracted", mealPlan: "Bed & Breakfast", roomingSummary: "—", ratePerNight: 235, nights: 2, selected: false, editable: true, optionId: "demo-set-1", cityTax: 5 },
      ],
    },
  ],
  experiences: [
    { id: "e1", name: "Amman Citadel & Roman Theatre", city: "Amman", type: "Entrance + Guide", day: "Day 2", status: "complete", amount: 240, included: true },
    { id: "e2", name: "Jerash archaeological site", city: "Jerash", type: "Entrance + Guide", day: "Day 2", status: "complete", amount: 560, included: true },
    { id: "e3", name: "Petra 2-day entrance pass", city: "Petra", type: "Entrance", day: "Day 4–5", status: "complete", amount: 3640, included: true },
    { id: "e4", name: "Petra by Night", city: "Petra", type: "Optional activity", day: "Day 4", status: "partial", amount: 476, included: false },
    { id: "e5", name: "Little Petra (Siq al-Barid)", city: "Wadi Rum", type: "Entrance", day: "Day 5", status: "complete", amount: 0, included: true },
    { id: "e6", name: "Wadi Rum 4x4 jeep safari", city: "Wadi Rum", type: "Activity", day: "Day 5", status: "missing", amount: 0, included: true },
    { id: "e7", name: "Bethany Beyond the Jordan", city: "Dead Sea", type: "Entrance + Guide", day: "Day 7", status: "complete", amount: 336, included: true },
  ],
  transport: [
    { id: "t1", route: "Queen Alia Airport → Amman hotel", type: "Transfer", day: "Day 1", vehicleClass: "Coach 35-seat", supplier: "Jordan Select Transport", supplierContract: "contracted", priceStatus: "complete", amount: 180, warning: null },
    { id: "t2", route: "Amman city tour & Jerash", type: "Touring", day: "Day 2", vehicleClass: "Coach 35-seat", supplier: "Jordan Select Transport", supplierContract: "contracted", priceStatus: "complete", amount: 420, warning: null },
    { id: "t3", route: "Amman → Petra via King's Highway", type: "Transfer", day: "Day 3", vehicleClass: "Coach 35-seat", supplier: "Jordan Select Transport", supplierContract: "contracted", priceStatus: "complete", amount: 560, warning: null },
    { id: "t4", route: "Wadi Rum 4x4 desert experience", type: "Touring", day: "Day 5", vehicleClass: "4x4 Jeeps × 7", supplier: "Unassigned", supplierContract: "no-contract", priceStatus: "missing", amount: null, warning: "No supplier assigned — desert 4x4 is unpriced" },
    { id: "t5", route: "Wadi Rum → Dead Sea", type: "Transfer", day: "Day 6", vehicleClass: "Coach 35-seat", supplier: "Jordan Select Transport", supplierContract: "contracted", priceStatus: "complete", amount: 640, warning: null },
    { id: "t6", route: "Dead Sea → Bethany Baptism Site (half day)", type: "Touring", day: "Day 7", vehicleClass: "Coach 35-seat", supplier: "Jordan Select Transport", supplierContract: "on-request", priceStatus: "partial", amount: 260, warning: "Rate provisional — awaiting supplier confirmation" },
    { id: "t7", route: "Dead Sea → Queen Alia Airport", type: "Transfer", day: "Day 8", vehicleClass: "Coach 35-seat", supplier: "Jordan Select Transport", supplierContract: "contracted", priceStatus: "complete", amount: 300, warning: null },
  ],
  passengers: [
    { id: "p1", fullName: "Maria Gonzalez", gender: "F", dateOfBirth: "12 Mar 1979", nationality: "Spain", passportNumber: "ESP4421987", passportExpiry: "30 Jun 2030", dietaryNotes: "Vegetarian", mobilityNotes: null, emergencyContact: "Luis Gonzalez +34 600 112 233", remarks: null },
    { id: "p2", fullName: "Luis Gonzalez", gender: "M", dateOfBirth: "02 Sep 1977", nationality: "Spain", passportNumber: "ESP4421988", passportExpiry: "30 Jun 2030", dietaryNotes: null, mobilityNotes: null, emergencyContact: null, remarks: null },
  ],
  roomingGroups: [
    { id: "r1", label: "Room 1", hotel: "Grand Hyatt Amman", day: "Day 1: Arrival Amman", roomType: "Deluxe", occupancyType: "double", guideRoom: false, leaderRoom: false, notes: null, passengers: ["Maria Gonzalez", "Luis Gonzalez"] },
  ],
  pricing: {
    lines: [
      { id: "c1", label: "Accommodation (7 nights)", amount: 31200, status: "partial", note: "Wadi Rum camp unselected · Dead Sea on request" },
      { id: "c2", label: "Transport", amount: 2360, status: "partial", note: "Wadi Rum 4x4 unpriced" },
      { id: "c3", label: "Experiences & entrances", amount: 5300, status: "partial", note: "Petra by Night & 4x4 pending" },
      { id: "c4", label: "Guide services (8 days)", amount: 4480, status: "complete", note: "English-speaking national guide" },
      { id: "c5", label: "Meals (per meal plan)", amount: 9800, status: "complete", note: "B daily, plus L/D per program" },
      { id: "c6", label: "Government taxes & service", amount: 5260, status: "complete", note: "Incl. Jordan Pass & 16% tax" },
    ],
    netCost: 58400,
    markupPercent: 16,
    margin: 9344,
    sellingPrice: 67744,
    pax: 28,
    perPerson: 2420,
    currency: "USD",
  },
  proposal: {
    included: [
      "7 nights in 5-star hotels and a luxury Wadi Rum desert camp",
      "Daily breakfast plus lunches and dinners as per the program",
      "Private air-conditioned coach throughout the tour",
      "Licensed English-speaking national guide for all touring days",
      "4x4 jeep experience and overnight in Wadi Rum",
      "All entrance fees listed in the itinerary (Jerash, Petra 2-day, Citadel, Bethany)",
      "Arrival and departure transfers at Queen Alia International Airport",
      "Jordan Pass, government taxes and service charges",
    ],
    excluded: [
      "International flights to and from Amman",
      "Travel insurance",
      "Personal expenses, drinks and gratuities",
      "Optional experiences such as Petra by Night unless confirmed",
      "Any service not specified in the program",
    ],
  },
  readiness: [
    { id: "p1", label: "Client, market language and rooming confirmed", done: true, step: "setup" },
    { id: "p2", label: "Itinerary complete for all 8 days", done: true, step: "itinerary" },
    { id: "p3", label: "All hotels assigned and contracted", done: false, step: "hotels" },
    { id: "p4", label: "Experiences and entrances confirmed", done: false, step: "experiences" },
    { id: "p5", label: "Transport priced for every service", done: false, step: "transport" },
    { id: "p6", label: "Pricing and margin approved", done: true, step: "pricing" },
  ],
}

/** An empty/blank quote shell, handy for testing empty states. */
export const emptyQuote: Quote = {
  ...demoQuote,
  itinerary: [],
  hotelCities: [],
  experiences: [],
  transport: [],
  passengers: [],
  roomingGroups: [],
  readiness: [],
  pricing: { ...demoQuote.pricing, lines: [], netCost: 0, margin: 0, sellingPrice: 0, perPerson: 0 },
}
