ALTER TABLE "vouchers" ALTER COLUMN "supplierId" DROP NOT NULL;

ALTER TYPE "VoucherType" ADD VALUE IF NOT EXISTS 'EXCURSION';
ALTER TYPE "VoucherStatus" ADD VALUE IF NOT EXISTS 'READY';
ALTER TYPE "VoucherStatus" ADD VALUE IF NOT EXISTS 'SENT';
