-- Track provenance of RouteStandard rows so the admin UI can distinguish
-- operator-curated entries from rows auto-generated by the bootstrap
-- action. Nullable + additive — legacy rows keep source = NULL.

ALTER TABLE "route_standards" ADD COLUMN "source" TEXT;
CREATE INDEX "route_standards_source_idx" ON "route_standards"("source");
